version: '3.4'
services:
  simplestore:
    build:
      context: .
      dockerfile: ./Dockerfile.Production
    image: 
      asasar/simplestore:v0.0.2
    ports:
    - "8001:8000"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings:SimpleAppConnection: Data Source=/dbSimplestore/simpleAppNetWeb.db
      #*************** SQL      *****************
      # ConnectionStrings:SimpleAppConnection: Server=<IP-public>;Database=simpleStore;Integrated Security=False;User Id=<User>;Password=<PASSWORD>;MultipleActiveResultSets=True
      # Data:useSqLite: "false"
      #*****************************************
      Data:useSqLite: "true"
      ASPNETCORE_URLS: http://*:8000
  simplestore-latest:
    build:
      context: .
      dockerfile: ./Dockerfile.Production
    image: 
      asasar/simplestore:latest 
    ports:
    - "8001:8000"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings:SimpleAppConnection: Data Source=/dbSimplestore/simpleAppNetWeb.db
      Data:useSqLite: "true"
      ASPNETCORE_URLS: http://*:8000
      #*************** SQL      *****************
      # ConnectionStrings:SimpleAppConnection: Server=<IP-public>;Database=simpleStore;Integrated Security=False;User Id=<User>;Password=<PASSWORD>;MultipleActiveResultSets=True
      # Data:useSqLite: "false"
      #*****************************************
